### ISSUE TITLE
Backwards compatiblity with 5.x versions

### ISSUE THREAD

**Issue by ghost** [transfer-framework/ezplatform#20]
@htollefsen As far as I understand this library will not work with 5.x versions as it requires 6.x version of eZ Publish (or eZ Platform 1.0 (?) ). Is there anything we could do to make this library compatible with 5.x, as well?

One option, is that we could move the `ezplatform` package (in the `composer.json` file) to the `suggest` block, and add the 5.x packages there, as well. This way developers can choose whichever version they prefer. But the big question is whether `transfer/ezplatform` will work for 5.x now and in the future, and whether it is worthwhile to support it?

**Comment by htollefsen** [comment]
It doesn't really require `ezsystems/ezplatform`, only `ezsystems/ezpublish-kernel`, though as you mention we've set the requirement to `~6.0.0`. As we can see in e.q. the [ContentTypeService](https://github.com/ezsystems/ezpublish-kernel/commits/master/eZ/Publish/API/Repository/ContentTypeService.php) there hasn't really been any breaking changes since.. a long time ago. I see no big issues with support for 5.4.x/v2014.11.x at the moment. Though that might change.

I'll re-run the tests with lowered dependencies, to see how things work out.

**Comment by htollefsen** [comment]
We'll need to add ezpublish legacy specific phpunit setup to do this, but my initial tests towards
`ezsystems/ezpublish-kernel@2014.11.8` and `ezsystems/ezpublish-legacy@2014.11.2` looked positive. Plenty of tests failed, because of a `doctrine/dbal` transaction problem, but it just seems like the legacy connection to some sort of database is non-existant. I'm sure we can just take a peak at ezsystems solution for this.

**Comment by ghost** [comment]
I've managed to fix the failing tests in #23.
