### ISSUE TITLE
Docs: Manifest example

### ISSUE THREAD

**Issue by nmeirik** [transfer-framework/ezplatform#43]
It would be useful to see a complete manifest example in the docs provided some type of generic input like a file or an array.

**Comment by htollefsen** [comment]
A source adapter which handles an array wouldn't really provide a good real use case (AFAI can think of). A source adapter which handles files already exists [for files](https://github.com/transfer-framework/transfer/blob/1.0/src/Transfer/Adapter/LocalFileAdapter.php) and for [directories](https://github.com/transfer-framework/transfer/blob/1.0/src/Transfer/Adapter/LocalDirectoryAdapter.php). So an example of what you want, should be really strait forward to present. What kinda of data do you suggest the file(s) should contain, and to what kind of source? 
That being said (the first line), I haven't really come up with the most easiest goto example, so any suggestion is highly receivable :+1:

**Comment by nmeirik** [comment]
As you can see from [the tutorial I'm working on](https://github.com/transfer-framework/examples/issues/5#issuecomment-180594581), my plan is to use a _very simple_ Spotify adapter. Then, I assume it makes sense to implement a worker converting the data it supplies to what eZ Platform expects. I'm a little fuzzy on how this would look as well.

**Comment by htollefsen** [comment]
Given [these lines in this manifest](https://github.com/transfer-framework/examples/blob/master/ezpublish/yaml_to_content_type/src/Transfer/Examples/YamlToEzPlatformContentType/Manifest/YamlToEzPlatformContentTypeManifest.php#L61-L76) as a shell:

You should do something along the lines of 

```
    ->createProcedure('songs')
        ->addSource(new SpotifyAdapter())
        ->addWorker(new SpotifyDataToTreeObjectWorker())
        ->addTarget(new EzPlatformAdapter(array('repository' => $this->repository)))
    ->end()
```

The SpotifyAdapter could return X number of SpotifySongDataObjects(?) formatted however you'd like, and in the Worker you have to change the data into something like this:

```
$song = new ContentObject(array(
    'title' => 'Jag Skulle Ge Vad Som Helst',
    'length' => 210,
));
$song->setContentType('song');
$song->setRemoteId('song_lasse_stefanz_jag_skulle_ge_vad_som_helst');
$song->setLanguage('eng-GB');

$artist = new ContentObject(array(
    'title' => 'Lasse Stefanz',
));
$artist->setContentType('artist');
$artist->setRemoteId('artist_lasse_stefanz');
$artist->setLanguage('eng-GB');

$tree = new TreeObject($artist);
$tree->setProperty('location_id', 2);
$tree->addNode($song);

return $tree;
```

It's given that you already have created or imported a contenttype `song` and `artist`, else you could just change it to `folder` and `article` which exists in ezplatform out of the box.
This is the best I can provide for now. It might be more preferable to use relations instead of this hierarchy structure, but I guess it's a good example.

**Comment by nmeirik** [comment]
Thanks, @htollefsen ! I'll see how far this will take me. Also, props for the Lasse Stefanz reference. :+1:

**Comment by htollefsen** [comment]
You're welcome, @nmeirik. 
Lasse Stefanz is indeed too rarely mentioned here on Github.
