### ISSUE TITLE
Consider defining actions as part of the request

### ISSUE THREAD

**Issue by ghost** [transfer-framework/ezplatform#93]
By defining `action`, such as create or delete, in an object, we mix data and application logic.

I suggest moving the `action` setting to a [Request](https://github.com/transfer-framework/transfer/blob/1.0/src/Transfer/Adapter/Transaction/Transaction.php) object.

Thus, a call to the eZ Publish adapter would look as follows:

```
$adapter->send(Request(
    array(new ContentObject(), ...),
    array('action' => Action::DELETE)
));
```

An immediate challenge with this approach is that it isn't possible to set the request headers in the procedure builder for target adapters.

This could be solved by either implementing a worker on the procedure level for providing a fixed set of headers that will be sent to the target, or by introducing something along the lines `RequestHeaderSetterAwareInterface` for workers, which will provide a method for returning request headers for each individual object.

**Comment by htollefsen** [comment]
To recap what we talked about, and to keep the history:

> This could be solved by either implementing a worker on the procedure level for providing a fixed set of headers that will be sent to the target

This will not let a developer create/update AND delete within the same procedure, so it's excluded as an option.

> introducing something along the lines `RequestHeaderSetterAwareInterface` for workers, which will provide a method for returning request headers for each individual object.

This is probably our best option, but old/current logic must be kept with a deprecation note otherwise it'll break BC. Also the interface must be implemented in [transfer/transfer](https://github.com/transfer-framework/transfer).
